---
title: "chccs_desegregation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r data}
demographics <- read.csv("chccs_demographics.csv")
chccs_aig <- read.csv("chccs_aig_lea.csv")
school_aig <- read.csv("chccs_aig_school.csv")
ap <- read.csv("chccs_ap.csv")
graduation <- read.csv("chccs_graduation.csv")
enrollment <- read.csv("chccs_enrollment.csv")
chccs_suspensions <- read.csv("chccs_suspensions_lea.csv")
school_suspensions <- read.csv("chccs_suspensions_school.csv")
```

```{r demographics}
# calculate demographic breakdown for CHCCS
chccs_demographics <- demographics %>% 
  group_by(year) %>% 
  summarize(year, white = sum(white_male + white_female), black = sum(black_male + black_female), 
            hispanic = sum(his_male + his_female), asian = sum(asian_male + asian_female), 
            pi = sum(pi_male + pi_female), aian = sum(aian_male + aian_female),
            multi = sum(multi_male + multi_female), total = sum(total)) %>% 
  mutate(pct_white = white / total * 100, pct_black = black / total * 100, pct_hispanic = hispanic / total * 100,
         pct_asian = asian / total * 100, pct_pi = pi / total * 100, pct_aian = aian / total * 100,
         pct_multi = multi / total * 100) %>% 
  select(year, pct_white, pct_black, pct_hispanic, pct_asian, pct_pi, pct_aian, pct_multi) %>% 
  unique()

# calculate demographic breakdown for each school
school_demographics <- demographics %>% 
  mutate(white = white_male + white_female, black = black_male + black_female, hispanic = his_male + his_female,
         asian = asian_male + asian_female, pi = pi_male + pi_female, aian = aian_male + aian_female,
         multi = multi_male + multi_female) %>% 
  select(year, school, white, black, hispanic, asian, pi, aian, multi, total) %>% 
  mutate(pct_white = white / total * 100, pct_black = black / total * 100, pct_hispanic = hispanic / total * 100,
         pct_asian = asian / total * 100, pct_pi = pi / total * 100, pct_aian = aian / total * 100,
         pct_multi = multi / total * 100) %>% 
  select(year, school, pct_white, pct_black, pct_hispanic, pct_asian, pct_pi, pct_aian, pct_multi)
```

```{r aig}
# calculate percentage differences between composition of district & AIG students
chccs_aig_num <- 3443
chccs_demographics %>% 
  filter(year == 2020) %>% 
  cbind(., chccs_aig %>% 
          pivot_wider(!pct, names_from = subgroup, values_from = num) %>% 
          summarize(aig_white = (white_female + white_male) / chccs_aig_num * 100, 
                    aig_black = (black_female + black_male) / chccs_aig_num * 100,
                    aig_hispanic = (his_female + his_male) / chccs_aig_num * 100, 
                    aig_asian = (asian_female + asian_male) / chccs_aig_num * 100,
                    aig_multi = (multi_female + multi_male) / chccs_aig_num * 100)) %>% 
  summarize(white_diff = aig_white - pct_white, black_diff = aig_black - pct_black, 
            hispanic_diff = aig_hispanic - pct_hispanic, asian_diff = aig_asian - pct_asian,
            multi_diff = aig_multi - pct_multi)

# calculate likelihood to be identified as AIG for district
chccs_aig %>% 
  pivot_wider(!pct, names_from = subgroup, values_from = num) %>% 
  summarize(aig_white = white_female + white_male, aig_black = black_female + black_male, 
            aig_hispanic = his_female + his_male, aig_asian = asian_female + asian_male, 
            aig_multi = multi_female + multi_male) %>% 
  cbind(., demographics %>% 
          filter(year == 2020) %>% 
          summarize(white = sum(white_male + white_female), black = sum(black_male + black_female), 
                    hispanic = sum(his_male + his_female), asian = sum(asian_male + asian_female), 
                    multi = sum(multi_male + multi_female))) %>% 
  summarize(pct_white = aig_white / white, pct_black = aig_black / black, pct_hispanic = aig_hispanic / hispanic,
            pct_asian = aig_asian / asian, pct_pi = pi, pct_multi = aig_multi / multi) %>% 
  summarize(black_dis = pct_white / pct_black, hispanic_dis = pct_white / pct_hispanic, 
            asian_dis = pct_white / pct_asian)

# calculate percentage differences between composition of school & AIG students
school_aig %>% 
  rename(aig_white = pct_white, aig_black = pct_black, aig_hispanic = pct_hispanic, aig_asian = pct_asian, 
         aig_pi = pct_pi, aig_aian = pct_aian, aig_multi = pct_multi) %>% 
  cbind(., school_demographics %>% 
          filter(year == 2018, school != "UNC Hospital School") %>% 
          select(-year, -school)) %>% 
  summarize(school, white_diff = aig_white - pct_white, black_diff = aig_black - pct_black, 
            hispanic_diff = aig_hispanic - pct_hispanic, asian_diff = aig_asian - pct_asian,
            multi_diff = aig_multi - pct_multi)
```

```{r ap}
# calculate percentage differences between composition of school & AP classes for each school
school_demographics %>% 
  filter(year == 2020, school %in% ap$school) %>% 
  cbind(., ap %>% 
          select(-year, -school) %>% 
          rename(ap_white = pct_white, ap_black = pct_black, ap_hispanic = pct_hispanic, ap_asian = pct_asian,
                 ap_pi = pct_pi, ap_aian = pct_aian, ap_multi = pct_multi)) %>% 
  summarize(year, school, white_diff = ap_white - pct_white, black_diff = ap_black - pct_black, 
            hispanic_diff = ap_hispanic - pct_hispanic, asian_diff = ap_asian - pct_asian, pi_diff = ap_pi - pct_pi,
            aian_diff = ap_aian - pct_aian, multi_diff = ap_multi - pct_multi)

# calculate likelihood to be in at least one AP class for each school
chs_ap_num <- 402 # Carrboro High School
chhs_ap_num <- 699 # Chapel Hill High School
echhs_ap_num <- 706 # East Chapel Hill High School

ap_demographics <- ap %>% 
  filter(school == "Carrboro High") %>% 
  summarize(school, white = round(pct_white / 100 * chs_ap_num), black = round(pct_black / 100 * chs_ap_num),
            hispanic = round(pct_hispanic / 100 * chs_ap_num), asian = round(pct_asian / 100 * chs_ap_num),
            pi = round(pct_pi / 100 * chs_ap_num), aian = round(pct_aian / 100 * chs_ap_num), 
            multi = round(pct_multi / 100 * chs_ap_num)) %>% 
  mutate(total = chs_ap_num) %>% 
  rbind(., ap %>% 
          filter(school == "Chapel Hill High") %>% 
          summarize(school, white = round(pct_white / 100 * chhs_ap_num), black = round(pct_black / 100 * chhs_ap_num),
                    hispanic = round(pct_hispanic / 100 * chhs_ap_num), asian = round(pct_asian / 100 * chhs_ap_num),
                    pi = round(pct_pi / 100 * chhs_ap_num), aian = round(pct_aian / 100 * chhs_ap_num),
                    multi = round(pct_multi / 100 * chhs_ap_num)) %>% 
          mutate(total = chhs_ap_num)) %>% 
  rbind(., ap %>% 
          filter(school == "East Chapel Hill High") %>% 
          summarize(school, white = round(pct_white / 100 * echhs_ap_num), black = round(pct_black / 100 * echhs_ap_num),
                    hispanic = round(pct_hispanic / 100 * echhs_ap_num), asian = round(pct_asian / 100 * echhs_ap_num),
                    pi = round(pct_pi / 100 * echhs_ap_num), aian = round(pct_aian / 100 * echhs_ap_num),
                    multi = round(pct_multi / 100 * echhs_ap_num)) %>% 
          mutate(total = echhs_ap_num))

demographics %>% 
  filter(year == 2020, school %in% ap$school) %>% 
  mutate(white = white_male + white_female, black = black_male + black_female, hispanic = his_male + his_female,
         asian = asian_male + asian_female, pi = pi_male + pi_female, aian = aian_male + aian_female,
         multi = multi_male + multi_female) %>% 
  select(year, school, white, black, hispanic, asian, pi, aian, multi, total) %>% 
  cbind(., ap_demographics %>% 
          select(-school) %>% 
          rename(ap_white = white, ap_black = black, ap_hispanic = hispanic, ap_asian = asian, ap_pi = pi, 
                 ap_aian = aian, ap_multi = multi, ap_total = total)) %>% 
  summarize(school, pct_white = ap_white / white, pct_black = ap_black / black, pct_hispanic = ap_hispanic / hispanic,
            pct_asian = ap_asian / asian, pct_pi = pi, pct_aian = ap_aian / aian, pct_multi = ap_multi / multi) %>% 
  summarize(school, black_dis = pct_white / pct_black, hispanic_dis = pct_white / pct_hispanic, 
            asian_dis = pct_white / pct_asian)
```

```{r achievement}
# calculate graduation rates for each school
graduation %>% 
  summarize(school, white_rate = white_grad / white_cohort * 100, black_rate = black_grad / black_cohort * 100,
            hispanic_rate = hispanic_grad / hispanic_cohort * 100, asian_rate = asian_grad / asian_cohort * 100,
            multi_rate = multi_grad / multi_cohort * 100)

# calculate likelihood to enroll in college for each school
enrollment %>% 
  summarize(school, black_dis = white_rate / black_rate, hispanic_dis = white_rate / hispanic_rate,
            asian_dis = white_rate / asian_rate)
```

```{r discipline}
# calculate percentage differences between composition of district & students experiencing short-term suspensions
chccs_demographics %>% 
  filter(year == 2020) %>% 
  cbind(., chccs_suspensions %>% 
          filter(year == 2020) %>% 
          summarize(sus_white = (white_female + white_male) / total * 100, 
                    sus_black = (black_female + black_male) / total * 100,
                    sus_hispanic = (his_female + his_male) / total * 100, 
                    sus_asian = (asian_female + asian_male) / total * 100,
                    sus_multi = (multi_female + multi_male) / total * 100)) %>% 
  summarize(white_diff = sus_white - pct_white, black_diff = sus_black - pct_black, 
            hispanic_diff = sus_hispanic - pct_hispanic, asian_diff = sus_asian - pct_asian,
            multi_diff = sus_multi - pct_multi)

# calculate likelihood to experience short-term suspension for district
chccs_suspensions %>% 
  filter(year == 2020) %>% 
  summarize(sus_white = white_female + white_male, sus_black = black_female + black_male, 
            sus_hispanic = his_female + his_male, sus_asian = asian_female + asian_male, 
            sus_multi = multi_female + multi_male) %>% 
  cbind(., demographics %>% 
          filter(year == 2020) %>% 
          summarize(white = sum(white_male + white_female), black = sum(black_male + black_female), 
                    hispanic = sum(his_male + his_female), asian = sum(asian_male + asian_female), 
                    multi = sum(multi_male + multi_female))) %>% 
  summarize(pct_white = sus_white / white, pct_black = sus_black / black, pct_hispanic = sus_hispanic / hispanic,
            pct_asian = sus_asian / asian, pct_pi = pi, pct_multi = sus_multi / multi) %>% 
  summarize(black_dis = pct_black / pct_white, hispanic_dis = pct_hispanic / pct_white, 
            asian_dis = pct_asian / pct_white)

# calculate likelihood to experience short-term suspension for each school
school_suspensions %>% 
  filter(!is.na(white_rate), white_rate > 0) %>% 
  summarize(school, black_dis = black_rate / white_rate) %>% 
  arrange(desc(black_dis))

# WHAT DOES STUDENT MEMBERSHIP MEAN??? THE ENTIRE STUDENT BODY??? THE NUMBER OF STUDENTS OF A GIVEN RACE???
# Rates per 1000 are calculated by dividing the total number of crimes or suspensions/expulsions by student membership at the State, District, or School level, and then multiplying by 1000. This statistic allows for general comparison of one entity to another by controlling for differences in student population size.
school_suspensions %>% 
  cbind(., demographics %>% 
          filter(year == 2020, school != "UNC Hospital School") %>% 
          select(total)) %>% 
  summarize(school, sus_white = round(white_rate / 1000 * total), sus_black = round(black_rate / 1000 * total),
            sus_hispanic = round(hispanic_rate / 1000 * total), sus_asian = round(asian_rate / 1000 * total),
            sus_multi = round(multi_rate / 1000)) %>% 
  cbind(., demographics %>% 
          filter(year == 2020, school != "UNC Hospital School") %>% 
          summarize(white = white_male + white_female, black = black_male + black_female, 
                    hispanic = his_male + his_female, asian = asian_male + asian_female, 
                    multi = multi_male + multi_female))

# over time
# data obscured for white_female in 2017 and 2014
chccs_suspensions %>% 
  summarize(year = year, white = white_female + white_male, black = black_female + black_male, total) %>% 
  mutate(pct_white = white / total * 100, pct_black = black / total * 100)
```
